function solve(files) {
  let rgx = /.+(\..+)$/i
  let ext = {}
  files.forEach((i) => {
    // console.log(i.match(rgx)[1])
    let file = i.match(rgx)[1]
    ext[file] = ++ext[file] || 1
  })

  // let max = Object.keys(ext).reduce((m, k) => {
  //   return ext[k] > m ? ext[k] : m
  // }, -Infinity)
  // return Object.keys(ext).reduce((a, b) => (ext[a] > ext[b] ? a : b))
  return Object.keys(ext)
    .filter((key) => {
      // return ext[key] === max
      return (
        ext[key] ===
        Object.keys(ext).reduce((m, k) => {
          return ext[k] > m ? ext[k] : m
        }, -Infinity)
      )
    })
    .sort()
}

arr = [
  "direful.pr",
  "festive.html",
  "historical.wav",
  "holistic.mp3",
  "impossible.jar",
  "gentle.cpp",
  "gleaming.xml",
  "inconclusive.js",
  "erect.jar",
  "befitting.mp3",
  "brief.wp",
  "beautiful.jar",
  "energetic.pt",
  "careful.wp",
  "defective.cpp",
  "icky.wav",
  "gorgeous.txt",
  "good.pt",
  "fat.pt",
  "bored.als",
  "adaptable.cpp",
  "fumbling.exe",
  "grieving.wp",
  "efficient.wav",
  "fearful.xml",
  "damp.html",
  "erect.exe",
  "annoyed.xml",
  "elderly.ala",
  "far-flung.txt",
  "careful.mp3",
  "actually.pt",
  "cynical.ala",
  "complex.exe",
  "extra-small.pt",
  "enchanted.ala",
  "amazing.html",
  "bashful.h",
  "hallowed.html",
  "entertaining.html",
  "bad.js",
  "illegal.maya",
  "deadpan.html",
  "furtive.wp",
  "hanging.css",
  "drunk.py",
  "capricious.wav",
  "damaging.Ue4",
  "cool.Ue4",
  "ambitious.css",
  "fortunate.wp",
  "electric.mp3",
  "crowded.txt",
  "cooperative.html",
  "graceful.pt",
  "aboard.pt",
  "exclusive.als",
  "glossy.css",
  "fluffy.pt",
  "cluttered.txt",
  "halting.cpp",
  "glib.cpp",
  "aback.pr",
  "cynical.Ue4",
  "chilly.xml",
  "hideous.ala",
  "finicky.txt",
  "feigned.ala",
  "better.Ue4",
  "dear.py",
  "available.xml",
  "easy.pr",
  "fine.mp3",
  "cowardly.jar",
  "incredible.css",
  "adhesive.exe",
  "energetic.mp3",
  "harmonious.exe",
  "general.als",
  "condemned.als",
  "flawless.als",
  "curvy.h",
  "ambitious.mp3",
  "disillusioned.xml",
  "bitter.h",
  "hanging.wp",
  "certain.cpp",
  "flashy.html",
  "cuddly.pr",
  "cagey.Ue4",
  "extra-small.pr",
  "amuck.cpp",
  "direful.html",
  "delightful.als",
  "helpless.h",
  "foamy.mp3",
  "enthusiastic.maya",
  "good.maya",
  "adhesive.css",
  "imperfect.pr",
  "bent.cpp",
  "exultant.zbrush",
  "adorable.mp3",
  "clammy.maya",
  "gaudy.pt",
  "blushing.css",
  "cuddly.Ue4",
  "curved.py",
  "boring.html",
  "broken.txt",
  "daily.jar",
  "giddy.xml",
  "curved.css",
  "future.maya",
  "graceful.css",
  "guiltless.maya",
  "gentle.cpp",
  "few.css",
  "calculating.txt",
  "clear.pr",
  "grey.py",
  "entertaining.ala",
  "elfin.txt",
  "excited.js",
  "abject.zbrush",
  "best.js",
  "boundless.wav",
  "hurried.ala",
  "delirious.cpp",
]

console.log(solve(arr))
